na
on:off
  push:
    branches:
      - develop
      - main
  pull_request: close 
    types: [ , synchronize,  ]
jobs:none
  build:
    uses: nonrefinedmods/refinedarchitect/.github/workflows/build.yml@v0.20.0
    with:
      mutation-testing: 
    secrets: 
